### ISSUE TITLE
I'm intrigued and I have some questions.

### ISSUE THREAD

**Issue by deslee** [subzerocloud/my-way-track#1]
I found this repository through a linked article posted on [Hacker News](https://news.ycombinator.com/item?id=39106901)

Since I'm not sure if the author is aware of the discussion, I want to repost my [comment](https://news.ycombinator.com/item?id=39110059) here:

Looking at this with an open mind, I'm curious what benefits running SQLite in WebAssembly with a proxied web worker API layer gives compared to using localStorage or something similar.
* Using SQL has clear benefits for writing an application. You can use existing stable tools for performing migrations.

* Using SQLite in a filesystem offers many advantages w.r.t performance and reliability. Do these advantages translate over when using WebAssembly SQLite over OPFS?

* How does SQLite / OPFS performance compare to reading / writing to localstorage?

* From what I know about web workers, the browser thinks it is making http requests to communicate with subzero, while the web worker proxies these requests to a local subzero server. What is the overhead cost with doing this, and what benefits does this give over having the browser communicate directly with SQLite?

* I remember seeing a demo of using [SQLite over HTTP](https://hn.algolia.com/?q=sqlite+http) a while back. I wonder if that can be implemented with web workers as an even simpler interface between the web and SQLite and how that affects bundle size...

**Comment by ruslantalpa** [comment]
replied there https://news.ycombinator.com/item?id=39110451
let me know if you have other questions
